# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_advancedsettings.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdvancedView(object):
    def setupUi(self, AdvancedView):
        AdvancedView.setObjectName("AdvancedView")
        AdvancedView.resize(696, 533)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(AdvancedView)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(AdvancedView)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.line_6 = QtWidgets.QFrame(AdvancedView)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_3.addWidget(self.line_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(AdvancedView)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.One_Column = QtWidgets.QSpinBox(AdvancedView)
        self.One_Column.setMinimum(-1)
        self.One_Column.setObjectName("One_Column")
        self.horizontalLayout_2.addWidget(self.One_Column)
        self.line_9 = QtWidgets.QFrame(AdvancedView)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_2.addWidget(self.line_9)
        self.label_7 = QtWidgets.QLabel(AdvancedView)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.Multiple_Column = QtWidgets.QCheckBox(AdvancedView)
        self.Multiple_Column.setText("")
        self.Multiple_Column.setObjectName("Multiple_Column")
        self.horizontalLayout_2.addWidget(self.Multiple_Column)
        self.line_10 = QtWidgets.QFrame(AdvancedView)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_2.addWidget(self.line_10)
        self.label_8 = QtWidgets.QLabel(AdvancedView)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.Combination_Column = QtWidgets.QLineEdit(AdvancedView)
        self.Combination_Column.setObjectName("Combination_Column")
        self.horizontalLayout_2.addWidget(self.Combination_Column)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.line_4 = QtWidgets.QFrame(AdvancedView)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(AdvancedView)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.repeat1 = QtWidgets.QRadioButton(AdvancedView)
        self.repeat1.setObjectName("repeat1")
        self.horizontalLayout.addWidget(self.repeat1)
        self.repeat2 = QtWidgets.QRadioButton(AdvancedView)
        self.repeat2.setObjectName("repeat2")
        self.horizontalLayout.addWidget(self.repeat2)
        self.repeat3 = QtWidgets.QRadioButton(AdvancedView)
        self.repeat3.setObjectName("repeat3")
        self.horizontalLayout.addWidget(self.repeat3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line_5 = QtWidgets.QFrame(AdvancedView)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(AdvancedView)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.checkBox_eval = QtWidgets.QCheckBox(AdvancedView)
        self.checkBox_eval.setObjectName("checkBox_eval")
        self.verticalLayout_3.addWidget(self.checkBox_eval)
        self.line_2 = QtWidgets.QFrame(AdvancedView)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(AdvancedView)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_13 = QtWidgets.QLabel(AdvancedView)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.com_conversion = QtWidgets.QComboBox(AdvancedView)
        self.com_conversion.setObjectName("com_conversion")
        self.com_conversion.addItem("")
        self.com_conversion.addItem("")
        self.com_conversion.addItem("")
        self.com_conversion.addItem("")
        self.com_conversion.addItem("")
        self.verticalLayout.addWidget(self.com_conversion)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(AdvancedView)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.slice1 = QtWidgets.QSpinBox(AdvancedView)
        self.slice1.setMinimum(0)
        self.slice1.setProperty("value", 0)
        self.slice1.setObjectName("slice1")
        self.horizontalLayout_8.addWidget(self.slice1)
        self.label_9 = QtWidgets.QLabel(AdvancedView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 0))
        self.label_9.setMaximumSize(QtCore.QSize(0, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.slice2 = QtWidgets.QSpinBox(AdvancedView)
        self.slice2.setMinimum(-1)
        self.slice2.setProperty("value", -1)
        self.slice2.setObjectName("slice2")
        self.horizontalLayout_8.addWidget(self.slice2)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.containerlistWidget = QtWidgets.QHBoxLayout()
        self.containerlistWidget.setObjectName("containerlistWidget")
        self.horizontalLayout_7.addLayout(self.containerlistWidget)
        self.contextlistWidget = QtWidgets.QListWidget(AdvancedView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contextlistWidget.sizePolicy().hasHeightForWidth())
        self.contextlistWidget.setSizePolicy(sizePolicy)
        self.contextlistWidget.setMinimumSize(QtCore.QSize(50, 200))
        self.contextlistWidget.setMaximumSize(QtCore.QSize(100, 200))
        self.contextlistWidget.setObjectName("contextlistWidget")
        item = QtWidgets.QListWidgetItem()
        self.contextlistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.contextlistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.contextlistWidget.addItem(item)
        self.horizontalLayout_7.addWidget(self.contextlistWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(AdvancedView)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_9.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_16 = QtWidgets.QLabel(AdvancedView)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(AdvancedView)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.pushtest = QtWidgets.QPushButton(AdvancedView)
        self.pushtest.setObjectName("pushtest")
        self.horizontalLayout_11.addWidget(self.pushtest)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.label_15 = QtWidgets.QLabel(AdvancedView)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.textEdit_deal = QtWidgets.QTextEdit(AdvancedView)
        self.textEdit_deal.setObjectName("textEdit_deal")
        self.verticalLayout_2.addWidget(self.textEdit_deal)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.line_3 = QtWidgets.QFrame(AdvancedView)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.label_11 = QtWidgets.QLabel(AdvancedView)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.line_7 = QtWidgets.QFrame(AdvancedView)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_3.addWidget(self.line_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(AdvancedView)
        self.label_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.contextlabel = QtWidgets.QLabel(AdvancedView)
        self.contextlabel.setMinimumSize(QtCore.QSize(0, 50))
        self.contextlabel.setText("")
        self.contextlabel.setObjectName("contextlabel")
        self.horizontalLayout_3.addWidget(self.contextlabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.line_8 = QtWidgets.QFrame(AdvancedView)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_3.addWidget(self.line_8)

        self.retranslateUi(AdvancedView)
        QtCore.QMetaObject.connectSlotsByName(AdvancedView)

    def retranslateUi(self, AdvancedView):
        _translate = QtCore.QCoreApplication.translate
        AdvancedView.setWindowTitle(_translate("AdvancedView", "结果处理设置"))
        self.label_3.setText(_translate("AdvancedView", "基础配置"))
        self.label_10.setText(_translate("AdvancedView", "单列："))
        self.label_7.setText(_translate("AdvancedView", "所有列："))
        self.label_8.setText(_translate("AdvancedView", "组合列："))
        self.Combination_Column.setPlaceholderText(_translate("AdvancedView", "1,100"))
        self.label_2.setText(_translate("AdvancedView", "结果去重："))
        self.repeat1.setText(_translate("AdvancedView", "无处理"))
        self.repeat2.setText(_translate("AdvancedView", "单例去重"))
        self.repeat3.setText(_translate("AdvancedView", "整条去重"))
        self.label_4.setText(_translate("AdvancedView", "操作选择"))
        self.checkBox_eval.setText(_translate("AdvancedView", "操作选择（默认为当前配置结果值处理）"))
        self.label.setText(_translate("AdvancedView", "配置结果值处理"))
        self.label_13.setText(_translate("AdvancedView", "翻译转换："))
        self.com_conversion.setItemText(0, _translate("AdvancedView", "不处理转换"))
        self.com_conversion.setItemText(1, _translate("AdvancedView", "转拼音"))
        self.com_conversion.setItemText(2, _translate("AdvancedView", "转英文"))
        self.com_conversion.setItemText(3, _translate("AdvancedView", "转拼音首字母大写"))
        self.com_conversion.setItemText(4, _translate("AdvancedView", "转英文首字母大写"))
        self.label_6.setText(_translate("AdvancedView", "截取："))
        self.label_9.setText(_translate("AdvancedView", "——"))
        __sortingEnabled = self.contextlistWidget.isSortingEnabled()
        self.contextlistWidget.setSortingEnabled(False)
        item = self.contextlistWidget.item(0)
        item.setText(_translate("AdvancedView", "原始内容"))
        item = self.contextlistWidget.item(1)
        item.setText(_translate("AdvancedView", "自增序号"))
        item = self.contextlistWidget.item(2)
        item.setText(_translate("AdvancedView", "补充值"))
        self.contextlistWidget.setSortingEnabled(__sortingEnabled)
        self.label_16.setText(_translate("AdvancedView", "函数结果值处理"))
        self.label_12.setText(_translate("AdvancedView", "通过eval字符串处理："))
        self.pushtest.setText(_translate("AdvancedView", "处理测试"))
        self.label_15.setText(_translate("AdvancedView", "函数编写"))
        self.textEdit_deal.setPlaceholderText(_translate("AdvancedView", "当前结果为val，字符串类型，生效后将不在使用配置结果处理。"))
        self.label_11.setText(_translate("AdvancedView", "结果"))
        self.label_5.setText(_translate("AdvancedView", "结果预览："))
